name: Publish

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.pusher.name, 'codecademy') != true
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: bahmutov/npm-install@v1
      - name: Update Version & Generate Changelog
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Codecademy[bot]'
          git-user-email: 'dev@codecademy.com'
          preset: conventionalcommits
          skip-on-empty: 'false'
      - name: Publish to NPM
        id: publish
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped == 'false'
        env:
         GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
         tag_name: ${{ steps.changelog.outputs.tag }}
         release_name: ${{ steps.changelog.outputs.tag }}
         body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.changelog.outputs.skipped == 'false'
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
